/*******************************************************************************
* Regenerate YAML Metadata Files Using Stata
* Date: 2026-01-24
* Purpose: Regenerate all YAML metadata files in stata/src/_/
*******************************************************************************/

clear all
set more off

* Get current directory and derive paths
local thisdir = c(pwd)
local statadir = subinstr("`thisdir'", "/qa", "", 1)
local statadir = subinstr("`statadir'", "\qa", "", 1)

di as text "{hline 78}"
di as result "{bf:{center 78:UNICEF METADATA YAML REGENERATION}}"
di as text "{hline 78}"
di as text ""
di as text "Starting metadata regeneration at: `c(current_date)' `c(current_time)'"
di as text "Stata directory: `statadir'"
di as text ""

* Install unicefdata from repo to ensure latest version
di as text "Installing unicefdata from repository..."
net install unicefdata, from("`statadir'") replace

* Display version
di as text ""
di as text "Installed unicefdata version: "
unicefdata, version

di as text ""
di as text "{hline 78}"
di as result "{bf:STEP 1: Full Metadata Sync}"
di as text "{hline 78}"
di as text ""
di as text "Running: unicefdata_sync, all verbose"
di as text "This will regenerate all YAML files in: `statadir'/src/_/"
di as text ""

* Capture start time
local sync_start = c(current_time)

* Run full sync with verbose output
cap noi unicefdata_sync, all verbose

local sync_rc = _rc
local sync_end = c(current_time)

di as text ""
if `sync_rc' == 0 {
    di as result "✓ Full metadata sync completed successfully"
} else {
    di as error "✗ Full metadata sync failed with error code: `sync_rc'"
}

di as text "Sync started: `sync_start'"
di as text "Sync ended:   `sync_end'"

* Verify output files exist
di as text ""
di as text "{hline 78}"
di as result "{bf:STEP 2: Verify Generated YAML Files}"
di as text "{hline 78}"
di as text ""

local yaml_dir "`statadir'/src/_"
local yaml_files "_unicefdata_dataflows.yaml _unicefdata_indicators.yaml _unicefdata_codelists.yaml _unicefdata_countries.yaml _unicefdata_regions.yaml _unicefdata_sync_history.yaml _unicefdata_indicators_metadata.yaml"

local files_ok = 0
local files_missing = 0

foreach file of local yaml_files {
    local filepath "`yaml_dir'/`file'"
    cap confirm file "`filepath'"
    if _rc == 0 {
        di as result "  ✓ `file'"
        local files_ok = `files_ok' + 1
    } else {
        di as error "  ✗ `file' - NOT FOUND"
        local files_missing = `files_missing' + 1
    }
}

di as text ""
di as text "Files verified: `files_ok' / " `=`files_ok'+`files_missing''
di as text "Files missing:  `files_missing'"

* Check dataflow schemas directory
di as text ""
di as text "Checking dataflow schemas in `yaml_dir'/__dataflows/..."
cap confirm file "`yaml_dir'/__dataflows/CME.yaml"
if _rc == 0 {
    di as result "  ✓ Dataflow schemas directory exists (sample: CME.yaml found)"
} else {
    di as text "  Note: Dataflow schemas not found (optional - generated by unicefdata_sync with dataflow index option)"
}

* Read and display metadata from one file
di as text ""
di as text "{hline 78}"
di as result "{bf:STEP 3: Sample Metadata Verification}"
di as text "{hline 78}"
di as text ""

local sample_file "`yaml_dir'/_unicefdata_dataflows.yaml"
cap confirm file "`sample_file'"
if _rc == 0 {
    di as text "Reading first 15 lines from: _unicefdata_dataflows.yaml"
    di as text "{hline 78}"

    tempname fh
    file open `fh' using "`sample_file'", read text
    local line_num = 0
    file read `fh' line
    while !r(eof) & `line_num' < 15 {
        local line_num = `line_num' + 1
        di as text "`line'"
        file read `fh' line
    }
    file close `fh'
    di as text "{hline 78}"
}

* Final summary
di as text ""
di as text "{hline 78}"
di as result "{bf:REGENERATION SUMMARY}"
di as text "{hline 78}"
di as text ""
di as text "Date:              `c(current_date)' `c(current_time)'"
di as text "Sync status:       " as result "`=cond(`sync_rc'==0, "SUCCESS", "FAILED")'"
di as text "Files generated:   `files_ok' / " `=`files_ok'+`files_missing''
di as text "Output directory:  `yaml_dir'"
di as text ""

if `sync_rc' == 0 & `files_missing' == 0 {
    di as result "✓✓✓ ALL YAML FILES SUCCESSFULLY REGENERATED ✓✓✓"
} else {
    di as error "✗✗✗ REGENERATION INCOMPLETE - CHECK ERRORS ABOVE ✗✗✗"
}

di as text "{hline 78}"

* Exit with appropriate code
exit `sync_rc'
