*! attributes() Option Usage Guide for wide_indicators
*! Version 1.5.1 - Testing and Examples
*! This file documents and tests the new attributes() option for flexible filtering

clear all
set more off

di ""
di "================================================================================"
di "attributes() Option for wide_indicators - Usage Guide"
di "================================================================================"
di ""

di "The attributes() option controls which disaggregation values to keep when"
di "using the wide_indicators reshape option."
di ""

di "Syntax:"
di "  unicefdata, indicator(...) countries(...) wide_indicators attributes(...) clear"
di ""

di "================================================================================"
di "1. DEFAULT BEHAVIOR - attributes() not specified or attributes(_T)"
di "================================================================================"
di ""
di "When you do NOT specify attributes(), the command defaults to keeping only"
di "the total (_T) for all disaggregations (sex, age, wealth, residence, matedu)."
di ""
di "Example:"
di "  unicefdata, indicator(CME_MRY0T4 IM_DTP3) countries(USA) year(2020) wide_indicators clear"
di ""
di "Expected result:"
di "  - iso3 and indicator columns"
di "  - Only _T (total) rows, no sex/age/wealth breakdown"
di "  - Example rows:"
di "    iso3   indicator      value"
di "    USA    CME_MRY0T4     85.5"
di "    USA    IM_DTP3        92.3"
di ""

di "================================================================================"
di "2. CUSTOM ATTRIBUTES - attributes(_M _F)"
di "================================================================================"
di ""
di "To keep specific attribute values, list them in attributes()."
di "This is useful when you need sex breakdown but not the full matrix."
di ""
di "Example:"
di "  unicefdata, indicator(CME_MRY0T4) countries(USA) year(2020) sex(ALL) ///
di "      wide_indicators attributes(_M _F) clear"
di ""
di "Expected behavior:"
di "  - Filters to keep only rows where sex == _M or sex == _F"
di "  - Drops rows where sex == _T (total)"
di "  - Result: 2 rows per iso3 (males and females only)"
di ""
di "Use cases:"
di "  - Sex disaggregation: attributes(_M _F) or attributes(_T _M _F)"
di "  - Wealth quintiles: attributes(_Q1 _Q2 _Q3 _Q4 _Q5)"
di "  - Mixed: attributes(_T _Q1 _Q2 _Q3 _Q4 _Q5) for total + poorest to richest"
di ""

di "================================================================================"
di "3. SPECIAL VALUE - attributes(ALL)"
di "================================================================================"
di ""
di "To keep all attribute combinations for all disaggregations, use attributes(ALL)."
di ""
di "Example:"
di "  unicefdata, indicator(CME_MRY0T4) countries(USA) year(2020) sex(ALL) ///
di "      age(ALL) wide_indicators attributes(ALL) clear"
di ""
di "Expected behavior:"
di "  - Keeps ALL combinations of sex and age"
di "  - Result: Many rows per iso3 (one for each sex × age combination)"
di ""
di "Use case: When you need full cross-tabulation of disaggregations"
di ""

di "================================================================================"
di "4. SUPPORTED ATTRIBUTE CODES"
di "================================================================================"
di ""
di "Sex disaggregation:"
di "  _T = Total"
di "  _M = Male"
di "  _F = Female"
di ""
di "Age disaggregation:"
di "  _T = Total"
di "  _0 = Age 0"
di "  _1 = Age 1-4"
di "  _5 = Age 5-9"
di "  _10 = Age 10-14"
di "  _15 = Age 15-17"
di "  _18 = Age 18-20"
di "  ... (age-specific codes as provided by indicator)"
di ""
di "Wealth quintile:"
di "  _T = Total"
di "  _Q1 = Poorest quintile"
di "  _Q2 = Second quintile"
di "  _Q3 = Middle quintile"
di "  _Q4 = Fourth quintile"
di "  _Q5 = Richest quintile"
di ""
di "Residence:"
di "  _T = Total"
di "  _U = Urban"
di "  _R = Rural"
di ""
di "Maternal education:"
di "  _T = Total"
di "  _NoEd = No education"
di "  _Prim = Primary education"
di "  _Sec = Secondary education"
di "  _High = Higher education"
di ""

di "================================================================================"
di "5. PRACTICAL EXAMPLES"
di "================================================================================"
di ""

di "Example A: Keep total and males for sex-disaggregated indicator"
di "  unicefdata, indicator(CME_MRY0T4) countries(USA BRA CHN) year(2020) ///
di "      sex(ALL) wide_indicators attributes(_T _M) clear"
di ""
di "Result:"
di "  - 6 rows (3 countries × 2 sex categories)"
di "  - Columns: iso3, country, period, CME_MRY0T4"
di ""

di "Example B: Get wealth quintile breakdown (no total)"
di "  unicefdata, indicator(HAZ_C19) countries(USA) year(2020) ///
di "      wealth(ALL) wide_indicators attributes(_Q1 _Q2 _Q3 _Q4 _Q5) clear"
di ""
di "Result:"
di "  - 5 rows (1 country × 5 wealth quintiles)"
di "  - Columns: iso3, country, period, HAZ_C19"
di ""

di "Example C: Full disaggregation matrix (sex and age)"
di "  unicefdata, indicator(U5M_C19) countries(USA) year(2020) ///
di "      sex(ALL) age(ALL) wide_indicators attributes(ALL) clear"
di ""
di "Result:"
di "  - Many rows (one for each sex × age combination)"
di "  - Columns: iso3, country, period, U5M_C19"
di ""

di "================================================================================"
di "6. IMPORTANT NOTES"
di "================================================================================"
di ""
di "• attributes() only affects wide_indicators reshape option"
di "• Does NOT apply to wide (years as columns) or wide_attributes (suffixes)"
di "• Default (_T) maintains backward compatibility with existing code"
di "• Multiple attribute codes must be space-separated (case-insensitive)"
di "• Invalid attribute codes are silently ignored"
di "• If no rows match the filter, all rows are kept (warning message)"
di ""

di "================================================================================"
di "End of Usage Guide"
di "================================================================================"
