setwd('C:/GitHub/myados/unicefData-dev')
devtools::load_all('.')
suppressMessages(library(dplyr))

# Test IM_DTP3 (should have 'vaccine' column)
cat("\n=== Testing IM_DTP3 ===\n")
df_r <- unicefData(indicator='IM_DTP3', countries='ALL', tidy=TRUE, include_label_columns=FALSE, cache=TRUE)
cols_r <- colnames(df_r)
cat("R columns for IM_DTP3 (", length(cols_r), "):\n", sep="")
print(cols_r)
cat("Has vaccine column?", 'vaccine' %in% cols_r, "\n")

# Test FD_EARLY_STIM (should have ethnic_group, education_level, disability_status, admin_level)
cat("\n=== Testing FD_EARLY_STIM ===\n")
df_r2 <- unicefData(indicator='FD_EARLY_STIM', countries='ALL', tidy=TRUE, include_label_columns=FALSE, cache=TRUE)
cols_r2 <- colnames(df_r2)
cat("R columns for FD_EARLY_STIM (", length(cols_r2), "):\n", sep="")
print(cols_r2)
cat("Has ethnic_group?", 'ethnic_group' %in% cols_r2, "\n")
cat("Has education_level?", 'education_level' %in% cols_r2, "\n")
cat("Has disability_status?", 'disability_status' %in% cols_r2, "\n")
cat("Has admin_level?", 'admin_level' %in% cols_r2, "\n")
